In [1]:
import numpy as np

a = np.random.randn(5)

In [3]:
print(a)

[ 1.10964286  0.82774263 -1.42820495  1.39630627 -1.96469215]


In [4]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[ 1.10964286  0.82774263 -1.42820495  1.39630627 -1.96469215]


In [6]:
print(np.dot(a,a.T))

9.765920966782497


In [7]:
a = np.random.randn(5,1)
print(a)

[[ 0.11397922]
 [ 0.08111652]
 [ 0.77814903]
 [ 0.29209322]
 [-0.65174155]]


In [8]:
print(a.shape)

(5, 1)


In [9]:
print(a.T)

[[ 0.11397922  0.08111652  0.77814903  0.29209322 -0.65174155]]


In [10]:
print(np.dot(a,a.T))

[[ 0.01299126  0.0092456   0.08869282  0.03329256 -0.07428499]
 [ 0.0092456   0.00657989  0.06312074  0.02369358 -0.052867  ]
 [ 0.08869282  0.06312074  0.60551591  0.22729206 -0.50715206]
 [ 0.03329256  0.02369358  0.22729206  0.08531845 -0.19036929]
 [-0.07428499 -0.052867   -0.50715206 -0.19036929  0.42476705]]


In [15]:
assert(a.shape == (5,1))

In [22]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [23]:
print(c.shape)

(3, 3)


In [25]:
u = a*b
v = a*c
w = b+c

In [27]:
J = u+v-w

In [ ]:
J = a*b + a*c - b -c